//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dislMagicGarden.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("dislMagicGarden.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die e.g. A brave squirrel saves the forest ähnelt.
        /// </summary>
        internal static string A_brave_squirrel_saves_the_forest {
            get {
                return ResourceManager.GetString("A_brave_squirrel_saves_the_forest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A magical adventure with ähnelt.
        /// </summary>
        internal static string A_magical_adventure_with {
            get {
                return ResourceManager.GetString("A_magical_adventure_with", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Access denied ähnelt.
        /// </summary>
        internal static string Access_denied {
            get {
                return ResourceManager.GetString("Access_denied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Adventurous ähnelt.
        /// </summary>
        internal static string Adventurous {
            get {
                return ResourceManager.GetString("Adventurous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Brothers Grimm ähnelt.
        /// </summary>
        internal static string Brothers_Grimm {
            get {
                return ResourceManager.GetString("Brothers_Grimm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Chapter ähnelt.
        /// </summary>
        internal static string Chapter {
            get {
                return ResourceManager.GetString("Chapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Classic German fairy tales ähnelt.
        /// </summary>
        internal static string Classic_German_fairy_tales {
            get {
                return ResourceManager.GetString("Classic_German_fairy_tales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Color ähnelt.
        /// </summary>
        internal static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Conjure up history ähnelt.
        /// </summary>
        internal static string Conjure_up_history {
            get {
                return ResourceManager.GetString("Conjure_up_history", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Contemporary and welcoming. ähnelt.
        /// </summary>
        internal static string Contemporary_and_welcoming {
            get {
                return ResourceManager.GetString("Contemporary_and_welcoming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Costs ähnelt.
        /// </summary>
        internal static string Costs {
            get {
                return ResourceManager.GetString("Costs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ✨ Create ähnelt.
        /// </summary>
        internal static string Create_button {
            get {
                return ResourceManager.GetString("Create_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dictate your fairy tale description ähnelt.
        /// </summary>
        internal static string Dictate_your_fairy_tale_description {
            get {
                return ResourceManager.GetString("Dictate_your_fairy_tale_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Duration ähnelt.
        /// </summary>
        internal static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Educational fairy tales ähnelt.
        /// </summary>
        internal static string Educational_fairy_tales {
            get {
                return ResourceManager.GetString("Educational_fairy_tales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 🎭 Fairy Tale Generator ähnelt.
        /// </summary>
        internal static string Fairy_Tale_Generator {
            get {
                return ResourceManager.GetString("Fairy_Tale_Generator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fairy tale type ähnelt.
        /// </summary>
        internal static string fairy_tale_type {
            get {
                return ResourceManager.GetString("fairy_tale_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fantasy ähnelt.
        /// </summary>
        internal static string fantasy {
            get {
                return ResourceManager.GetString("fantasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Funny ähnelt.
        /// </summary>
        internal static string Funny {
            get {
                return ResourceManager.GetString("Funny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Generate fairy tales ähnelt.
        /// </summary>
        internal static string Generate_fairy_tales {
            get {
                return ResourceManager.GetString("Generate_fairy_tales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die H. C. Andersen ähnelt.
        /// </summary>
        internal static string H_C_Andersen {
            get {
                return ResourceManager.GetString("H_C_Andersen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create new story ähnelt.
        /// </summary>
        internal static string Home_NewStory {
            get {
                return ResourceManager.GetString("Home_NewStory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Welcome to MagicGarden ähnelt.
        /// </summary>
        internal static string Home_Welcome {
            get {
                return ResourceManager.GetString("Home_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Humorous stories ähnelt.
        /// </summary>
        internal static string Humorous_stories {
            get {
                return ResourceManager.GetString("Humorous_stories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insufficient credit. Please purchase more to continue using the service. ähnelt.
        /// </summary>
        internal static string insufficient_credit {
            get {
                return ResourceManager.GetString("insufficient_credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Language ähnelt.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Luna is waiting for a new adventure! ähnelt.
        /// </summary>
        internal static string Luna_is_waiting {
            get {
                return ResourceManager.GetString("Luna_is_waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Magical worlds and creatures ähnelt.
        /// </summary>
        internal static string Magical_worlds_and_creatures {
            get {
                return ResourceManager.GetString("Magical_worlds_and_creatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Microphone access is required ähnelt.
        /// </summary>
        internal static string Microphone_access_is_required {
            get {
                return ResourceManager.GetString("Microphone_access_is_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mode ähnelt.
        /// </summary>
        internal static string Mode {
            get {
                return ResourceManager.GetString("Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Modern fairy tales ähnelt.
        /// </summary>
        internal static string Modern_fairy_tales {
            get {
                return ResourceManager.GetString("Modern_fairy_tales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Story ähnelt.
        /// </summary>
        internal static string NewStory {
            get {
                return ResourceManager.GetString("NewStory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Animal friend ähnelt.
        /// </summary>
        internal static string NewStory_Animal {
            get {
                return ResourceManager.GetString("NewStory_Animal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Child’s Name ähnelt.
        /// </summary>
        internal static string NewStory_ChildName {
            get {
                return ResourceManager.GetString("NewStory_ChildName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mood ähnelt.
        /// </summary>
        internal static string NewStory_Mood {
            get {
                return ResourceManager.GetString("NewStory_Mood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Magical world ähnelt.
        /// </summary>
        internal static string NewStory_World {
            get {
                return ResourceManager.GetString("NewStory_World", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter a topic ähnelt.
        /// </summary>
        internal static string Please_enter_a_topic {
            get {
                return ResourceManager.GetString("Please_enter_a_topic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Poetic fairy tales with feeling ähnelt.
        /// </summary>
        internal static string Poetic_fairy_tales_with_feeling {
            get {
                return ResourceManager.GetString("Poetic_fairy_tales_with_feeling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 🔊 Read aloud ähnelt.
        /// </summary>
        internal static string Read_aloud {
            get {
                return ResourceManager.GetString("Read_aloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reading voice ähnelt.
        /// </summary>
        internal static string reading_voice {
            get {
                return ResourceManager.GetString("reading_voice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ready ähnelt.
        /// </summary>
        internal static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reassuring ähnelt.
        /// </summary>
        internal static string Reassuring {
            get {
                return ResourceManager.GetString("Reassuring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die seconds ähnelt.
        /// </summary>
        internal static string seconds {
            get {
                return ResourceManager.GetString("seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select ähnelt.
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select duration ähnelt.
        /// </summary>
        internal static string Select_duration {
            get {
                return ResourceManager.GetString("Select_duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select language ähnelt.
        /// </summary>
        internal static string Select_language {
            get {
                return ResourceManager.GetString("Select_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select style ähnelt.
        /// </summary>
        internal static string Select_style {
            get {
                return ResourceManager.GetString("Select_style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 📤 Share ähnelt.
        /// </summary>
        internal static string Share_button {
            get {
                return ResourceManager.GetString("Share_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Share fairy tales ähnelt.
        /// </summary>
        internal static string Share_fairy_tales {
            get {
                return ResourceManager.GetString("Share_fairy_tales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Speak now... ähnelt.
        /// </summary>
        internal static string Speak_now {
            get {
                return ResourceManager.GetString("Speak_now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Speed ähnelt.
        /// </summary>
        internal static string speed {
            get {
                return ResourceManager.GetString("speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stop ähnelt.
        /// </summary>
        internal static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Story length (minutes) ähnelt.
        /// </summary>
        internal static string Story_length {
            get {
                return ResourceManager.GetString("Story_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Style ähnelt.
        /// </summary>
        internal static string Style {
            get {
                return ResourceManager.GetString("Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Theme of your fairy tale ähnelt.
        /// </summary>
        internal static string Theme_of_your_fairy_tale {
            get {
                return ResourceManager.GetString("Theme_of_your_fairy_tale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Undo ähnelt.
        /// </summary>
        internal static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Values and knowledge through play ähnelt.
        /// </summary>
        internal static string Values_and_knowledge_through_play {
            get {
                return ResourceManager.GetString("Values_and_knowledge_through_play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your description appears here ähnelt.
        /// </summary>
        internal static string Your_description_appears_here {
            get {
                return ResourceManager.GetString("Your_description_appears_here", resourceCulture);
            }
        }
    }
}
